<div class="container-fluid py-2 px-3 fixed-top d-flex">
    <?php if (!empty($_SESSION)) : ?>
        <div class="dropdown ms-auto">
            <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="#FFFFFF" viewBox="0 0 256 256">
                    <path d="M230.92,212c-15.23-26.33-38.7-45.21-66.09-54.16a72,72,0,1,0-73.66,0C63.78,166.78,40.31,185.66,25.08,212a8,8,0,1,0,13.85,8c18.84-32.56,52.14-52,89.07-52s70.23,19.44,89.07,52a8,8,0,1,0,13.85-8ZM72,96a56,56,0,1,1,56,56A56.06,56.06,0,0,1,72,96Z"></path>
                </svg>
                <?php echo $_SESSION['email'] ?>
            </button>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="/">Strona główna</a></li>
                <li><a class="dropdown-item" href="account">Moje rezerwacje</a></li>
                <li><a class="dropdown-item" href="edit">Zmiana hasla</a></li>
                <?php if ($_SESSION['is_admin']) : ?>
                    <li><a class="dropdown-item" href="admin">Panel administratora</a></li>
                <?php endif; ?>
                <!--<li><hr class="dropdown-divider"></li>-->
                <li><a class="dropdown-item" href="login/logout">Wyloguj</a></li>
            </ul>
        </div>
    <?php else : ?>
        <a href="/login" class="btn btn-primary ms-auto">
            <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="#000000" viewBox="0 0 256 256">
                <path d="M230.92,212c-15.23-26.33-38.7-45.21-66.09-54.16a72,72,0,1,0-73.66,0C63.78,166.78,40.31,185.66,25.08,212a8,8,0,1,0,13.85,8c18.84-32.56,52.14-52,89.07-52s70.23,19.44,89.07,52a8,8,0,1,0,13.85-8ZM72,96a56,56,0,1,1,56,56A56.06,56.06,0,0,1,72,96Z"></path>
            </svg>Zaloguj się
        </a>
    <?php endif; ?>
</div>