<body>
    <div class="background">
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
    </div>
    <div class="container-fluid form-fluid-container d-flex justify-content-center pt-5 vh-100 align-items-center">
        <div class="form-container">
            <a href="./">
                <h1 class="fs-5 mb-3 text-white">Cinefy</h1>
            </a>
            <p>Rejestracja</p>
            <?php
            if (!empty($results)) {
                \Cinefy::addMessage($results['result'], $results['message']);
            }

            ?>
            <form method="post" id="registerForm">
                <label for="email">Email</label>
                <input type="email" class="form-control" name="email" id="email">
                <label for="email">Haslo</label>
                <input type="password" class="form-control" placeholder="min. 6 znaków" name="password" id="password">
                <label for="email">Potwierdz haslo</label>
                <input type="password" class="form-control" name="repassword" id="repassword">
                <input type="submit" class="btn btn-primary w-100" value="Zarejestruj sie">
            </form>
            <a href="login" class="btn btn-secondary w-100">Powrót do logowania</a>
        </div>
    </div>
</body>