<!DOCTYPE html>
<html lang="pl">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Cinefy</title>
    <link rel="stylesheet" href="vendor/css/bootstrap/bootstrap.min.css">
    <link rel="stylesheet" href="assets/css/style.css">
    <link rel="icon" type="image/x-icon" href="assets/img/favicon.ico">
    <script src="vendor/js/jquery/jquery.min.js"></script>
    <script src="vendor/js/bootstrap/bootstrap.bundle.min.js"></script>
</head>